In [1]:
import numpy as np

### Numpy Array:

In [2]:
a = np.array([1, 2, 3])
a + a

array([2, 4, 6])

In [3]:
def print_array_details(a):
    print('Dimensions: %d, shape: %s, dtype: %s'\
        %(a.ndim, a.shape, a.dtype))

In [10]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
print_array_details(a)

Dimensions: 1, shape: (8,), dtype: int32


In [8]:
a = a.reshape([2, 4])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
print_array_details(a)

Dimensions: 2, shape: (2, 4), dtype: int32


In [6]:
a = a.reshape([2, 2, 2])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
print_array_details(a)

Dimensions: 3, shape: (2, 2, 2), dtype: int32


In [13]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
x.shape

(2, 3)

In [14]:
x.shape = (6,)
x

array([1, 2, 3, 4, 5, 6])

In [15]:
x = x.astype('int64')
x.dtype

dtype('int64')

### Creating Arrays:

In [16]:
a = np.zeros([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
a.dtype

dtype('float64')

In [18]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
empty_array = np.empty((2,3))
empty_array

array([[0.89583772, 0.55979688, 0.16898596],
       [0.37955196, 0.45214329, 0.94426809]])

- A 2×3 array of random numbers within the range 0 <= x < 1.

In [21]:
np.random.random((2,3))

array([[0.89583772, 0.55979688, 0.16898596],
       [0.37955196, 0.45214329, 0.94426809]])

In [24]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [25]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

### Array Indexing and Slicing:

In [26]:
a = np.array([1, 2, 3, 4, 5, 6])
a[2]

3

In [27]:
a[3:5]

array([4, 5])

In [29]:
a[:4:2] = 0

In [30]:
a[::-1]

array([6, 5, 4, 0, 2, 0])

In [33]:
a = np.arange(8)
a.shape = (2, 2, 2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
a1 = a[1]
a1

array([[4, 5],
       [6, 7]])

In [36]:
np.array_equal(a1, a[1,:])

True

In [37]:
np.array_equal(a1, a[1,:,:])

True

### A Few Basic Operations: 

In [39]:
a = np.array([45, 65, 76, 32, 99, 22])
a < 50

array([ True, False, False,  True, False,  True])

In [40]:
a = np.arange(8).reshape((2,4))

In [41]:
a.min(axis=1)

array([0, 4])

In [42]:
a.sum(axis=0)

array([ 4,  6,  8, 10])

In [43]:
a.mean(axis=1)

array([1.5, 5.5])

In [44]:
a.std(axis=1)

array([1.11803399, 1.11803399])

In [45]:
pi = np.pi
a = np.array([pi, pi/2, pi/4, pi/6])

np.degrees(a)

array([180.,  90.,  45.,  30.])